apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
 kind: Ingress
 metadata:
   name: todoapp-ingress
   namespace: app
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: todo-app.info
     http:
       paths:
       - path: /
         backend:
           serviceName: todoapp
           servicePort: 3000